# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - new-feature
    - title: Bug Fixes
      labels:
        - bug-fix
    - title: Other Changes
      labels:
        - "*"
